language: groovy

jdk:
- oraclejdk7
- openjdk7
- openjdk6

before_install:
- sudo add-apt-repository -y ppa:groovy-dev/grails
- sudo apt-get update
- sudo apt-get install grails-1.3.7

script: "grails test-app unit: --non-interactive"