site_name: OpenBoxes
site_description: 
site_author: Justin Miranda
theme: readthedocs
repo_url: https://github.com/openboxes/openboxes
include_search: true
#use_absolute_urls: true
use_directory_urls: true
copyright: Copyright &copy; 2017, OpenBoxes
google_analytics: ['UA-37396941-2', 'OpenBoxes']

pages:

- Home: 'index.md'

- About:
    - 'Benefits': 'about/benefits.md'
    - 'Considerations': 'about/considerations.md'
    - 'Release Notes': 'about/release-notes.md'

- API Guide:
    - 'Overview': 'api-guide/index.md'
    - 'Generic': 'api-guide/generic.md'
    - 'Category': 'api-guide/category.md'
    - 'Identifier': 'api-guide/identifier.md'
    - 'Location': 'api-guide/location.md'
    - 'Lookup': 'api-guide/lookup.md'
    - 'Product': 'api-guide/product.md'
    - 'Stock Movement': 'api-guide/stockMovement.md'
    - 'Stock Movement Item': 'api-guide/stockMovementItem.md'
    - 'Stock Movement Status': 'api-guide/stockMovementStatus.md'

- Deployment Guide:
    - 'Installation': 'installation/index.md'
    - 'Install on Ubuntu 14.04': 'installation/ubuntu.md'
    - 'Install on Mac OS': 'installation/macos.md'
    - 'Install on Windows': 'installation/windows.md'
    - 'Upgrading': 'upgrading/index.md'

- Configuration Guide:
    - 'General': 'configuration/configuration.md'
    - 'Database': 'configuration/database.md'
    - 'Email': 'configuration/email.md'
    - 'Application': 'configuration/application.md'
    - 'Example': 'configuration/example.md'

- User Guide: 'user-guide/index.md'

- Developer Guide:
    - 'Introduction': 'developer-guide/index.md'
    - 'Getting Started': 'developer-guide/getting-started.md'
    - 'Contributing': 'developer-guide/contributing.md'
    - 'Syncing a Fork': 'developer-guide/syncing-a-fork.md'
    - 'Tagging a Release': 'developer-guide/tagging.md'

- Support: 'support/index.md'


