site_name: OpenBoxes
site_description:
site_author: Justin Miranda
repo_url: https://github.com/openboxes/openboxes
theme: readthedocs
include_search: true
#use_absolute_urls: true
use_directory_urls: true
copyright: Copyright &copy; 2010-2019, OpenBoxes
google_analytics: ['UA-37396941-2', 'openboxes.com']
markdown_extensions:
  - admonition
  - footnotes
  - tables
nav:
  - Home: index.md
  - About:
    - Features: https://openboxes.com/features/
    - Architecture: about/architecture.md
    - Benefits: about/benefits.md
    - Considerations: about/considerations.md
    - Pricing: https://openboxes.com/pricing/
    - Road Map: https://openboxes.com/roadmap/
    - Release Notes: about/release-notes.md
  - Installation:
    - Overview: installation/index.md
    - Ubuntu 18.04:
      - Overview: installation/ubuntu1804/index.md
      - Hosting: installation/ubuntu1804/hosting.md
      - Ubuntu: installation/ubuntu1804/ubuntu.md
      - Java: installation/ubuntu1804/java.md
      - Tomcat: installation/ubuntu1804/tomcat.md
      - MySQL: installation/ubuntu1804/mysql.md
      - Apache: installation/ubuntu1804/apache.md
      - Configuration: installation/ubuntu1804/configuration.md
      - Deployment: installation/ubuntu1804/deployment.md
      - Troubleshooting: installation/ubuntu1804/troubleshooting.md
    - Ubuntu 16.04:
      - Instructions: installation/ubuntu1604.md
      - Notes: installation/ubuntu1604-notes.md
    - Ubuntu 14.04: installation/ubuntu1404.md
    - Docker: installation/docker.md
    - Mac OS: installation/macos.md
    - Windows: installation/windows.md
    - Upgrading: upgrading/index.md
  - Configuration:
    - Overview: configuration/index.md
    - Tomcat AJP: configuration/ajp.md
    - Apache HTTPS: configuration/https.md
    - Database Connection: configuration/database.md
    - Email: configuration/email.md
    - OpenBoxes: configuration/application.md
    - Sentry: configuration/sentry.md
    - Example: configuration/example.md
  - Users:
    - Overview: user-guide/index.md
  - Developers:
    - Introduction: developer-guide/index.md
    - Release Process: developer-guide/release-process.md
    - Getting Started: developer-guide/getting-started.md
    - Contributing: developer-guide/contributing.md
    - Syncing a Fork: developer-guide/syncing-a-fork.md
    - Tagging a Release: developer-guide/tagging.md
    - Troubleshooting: developer-guide/troubleshooting.md
  - REST API Guide:
    - Overview: api-guide/index.md
    - Getting Started: api-guide/getting-started.md
    - Generic API: api-guide/generic.md
    - Custom API:
        - Core:
            - Identifiers: api-guide/identifier.md
            - Internal Locations: api-guide/internalLocation.md
            - Localizations: api-guide/localization.md
            - Locations: api-guide/location.md
            - Lookup: api-guide/lookup.md
            - Reason Codes: api-guide/reasonCode.md
        - Products:
            - Categories: api-guide/category.md
            - Products: api-guide/product.md
        - Stock Movements:
            - Stock Movement: api-guide/stockMovement.md
            - Stock Movement Item: api-guide/stockMovementItem.md
            - Stock Movement Status: api-guide/stockMovementStatus.md
            - Putaway: api-guide/putaway.md
            - Receiving: api-guide/receiving.md
  - Support:
    - Overview: support/index.md


