site_name: OpenBoxes
site_description: 
site_author: Justin Miranda
theme: readthedocs
repo_url: https://github.com/openboxes/openboxes
include_search: true
#use_absolute_urls: true
use_directory_urls: true
copyright: Copyright &copy; 2017, OpenBoxes
google_analytics: ['UA-37396941-2', 'OpenBoxes']

pages:

# About:
- ['index.md', 'About', 'Introduction']
- ['benefits.md', 'About', 'Benefits']
- ['drawbacks.md', 'About', 'Drawbacks']

# Installation
- ['installation/index.md', 'Installation',  'Overview']
- ['installation/ubuntu.md', 'Installation', 'Ubuntu']
- ['installation/macos.md', 'Installation', 'Mac OS']
- ['installation/windows.md', 'Installation', 'Windows']

# Configuration
- ['configuration.md', 'Configuration Guide', 'Configuration']

# Configuration
- ['user-guide/introduction.md', 'User Guide', 'Introduction']

# Developer Guide
- ['developer-guide/introduction.md', 'Developer Guide', 'Introduction']
- ['developer-guide/getting-started.md', 'Developer Guide', 'Getting Started']
- ['developer-guide/contributing.md', 'Developer Guide', 'Contributing']
- ['developer-guide/syncing-a-fork.md', 'Developer Guide', 'Syncing a Fork']
- ['developer-guide/tagging.md', 'Developer Guide', 'Tagging a Release']

# Support - add a page like https://readthedocs.org/support/

# Continuous Integration
# User Guide
# HowTo
# Cloud

# Releases:
- ['release-notes.md', 'Releases', 'Release Notes']


