site_name: OpenBoxes
site_description: 
site_author: Justin Miranda
theme: readthedocs
repo_url: https://github.com/openboxes/openboxes
#include_search: true
#use_absolute_urls: true
use_directory_urls: true
copyright: Copyright &copy; 2018, OpenBoxes
google_analytics: ['UA-37396941-2', 'OpenBoxes']

pages:

- Home: 'index.md'
- 'Benefits': 'benefits.md'
- 'Considerations': 'considerations.md'
- 'Release Notes': 'release-notes.md'
- Installation Guide:
    - 'Installation': 'installation/index.md'
    - 'Install on Ubuntu': 'installation/ubuntu.md'
    - 'Install on Mac OS': 'installation/macos.md'
    - 'Install on Windows': 'installation/windows.md'
    - 'Upgrading': 'upgrading/index.md'
- Configuration Guide:
    - 'General': 'configuration/configuration.md'
    - 'Database': 'configuration/database.md'
    - 'Email': 'configuration/email.md'
    - 'Application': 'configuration/application.md'
    - 'Example': 'configuration/example.md'
- User Guide: 'user-guide/index.md'
- Developer Guide:
    - 'Introduction': 'developer-guide/index.md'
    - 'Getting Started': 'developer-guide/getting-started.md'
    - 'Contributing': 'developer-guide/contributing.md'
    - 'Syncing a Fork': 'developer-guide/syncing-a-fork.md'
    - 'Tagging a Release': 'developer-guide/tagging.md'

#    - REST API Guide:
#        - 'Overview': 'api-guide/index.md'
#        - 'Getting Started': 'api-guide/getting-started.md'
#        - 'Generic API': 'api-guide/generic.md'
#        - 'Custom API':
#            - 'Categories': 'api-guide/category.md'
#            - 'Identifiers': 'api-guide/identifier.md'
#            - 'Internal Locations': 'api-guide/internalLocation.md'
#            - 'Locations': 'api-guide/location.md'
#            - 'Lookup': 'api-guide/lookup.md'
#            - 'Products': 'api-guide/product.md'
#            - 'Putaway': 'api-guide/putaway.md'
#            - 'Receiving': 'api-guide/receiving.md'
#            - 'Stock Movements':
#                - 'Stock Movement': 'api-guide/stockMovement.md'
#                - 'Stock Movement Item': 'api-guide/stockMovementItem.md'
#                - 'Stock Movement Status': 'api-guide/stockMovementStatus.md'

- Support: 'support/index.md'


